# docker-compose.yml
version: '3.8'

services:
  # api:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: payment-api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/payment_db?schema=public
  #     - JWT_SECRET=yoursecretkey
  #     - GOOGLE_CLIENT_ID=your_google_client_id
  #     - GOOGLE_CLIENT_SECRET=your_google_client_secret
  #     - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
  #     - PORT=3000
  #   depends_on:
  #     - db
  #   networks:
  #     - payment-network

  db:
    image: postgres:15
    container_name: payment-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: payment-frontend
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:3000
  #     - NEXT_PUBLIC_GOOGLE_CLIENT_ID=your_google_client_id
  #   depends_on:
  #     - api
  #   networks:
  #     - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  postgres_data:
